// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/history">> = Specific
  const handler = {} as typeof import("../../../src/app/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/payments/sandbox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payments/sandbox">> = Specific
  const handler = {} as typeof import("../../../src/app/payments/sandbox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/reigns/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reigns/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/reigns/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/assets/[...key]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assets/[...key]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/assets/[...key]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/assets/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assets/upload">> = Specific
  const handler = {} as typeof import("../../../src/app/api/assets/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/contributors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contributors">> = Specific
  const handler = {} as typeof import("../../../src/app/api/contributors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/coronation/identity/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/coronation/identity">> = Specific
  const handler = {} as typeof import("../../../src/app/api/coronation/identity/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/defense/place/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/defense/place">> = Specific
  const handler = {} as typeof import("../../../src/app/api/defense/place/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events">> = Specific
  const handler = {} as typeof import("../../../src/app/api/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/history">> = Specific
  const handler = {} as typeof import("../../../src/app/api/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/payments/attack-checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/attack-checkout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/payments/attack-checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/payments/dodo-webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/dodo-webhook">> = Specific
  const handler = {} as typeof import("../../../src/app/api/payments/dodo-webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/payments/sandbox-confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/sandbox-confirm">> = Specific
  const handler = {} as typeof import("../../../src/app/api/payments/sandbox-confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/payments/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/status">> = Specific
  const handler = {} as typeof import("../../../src/app/api/payments/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/recovery/claim/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recovery/claim">> = Specific
  const handler = {} as typeof import("../../../src/app/api/recovery/claim/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/recovery/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recovery/create">> = Specific
  const handler = {} as typeof import("../../../src/app/api/recovery/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/reigns/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reigns/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/reigns/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/session">> = Specific
  const handler = {} as typeof import("../../../src/app/api/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/share-card/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/share-card/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/share-card/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/siege/attack/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/siege/attack">> = Specific
  const handler = {} as typeof import("../../../src/app/api/siege/attack/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/siege/entitlements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/siege/entitlements">> = Specific
  const handler = {} as typeof import("../../../src/app/api/siege/entitlements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/siege/queue/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/siege/queue">> = Specific
  const handler = {} as typeof import("../../../src/app/api/siege/queue/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/siege/turn/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/siege/turn/cancel">> = Specific
  const handler = {} as typeof import("../../../src/app/api/siege/turn/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/siege/turn/claim/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/siege/turn/claim">> = Specific
  const handler = {} as typeof import("../../../src/app/api/siege/turn/claim/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/world/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/world">> = Specific
  const handler = {} as typeof import("../../../src/app/api/world/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
