// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/history" | "/payments/sandbox" | "/privacy" | "/reigns/[id]" | "/terms"
type AppRouteHandlerRoutes = "/api/assets/[...key]" | "/api/assets/upload" | "/api/contributors" | "/api/coronation/identity" | "/api/defense/place" | "/api/events" | "/api/history" | "/api/payments/attack-checkout" | "/api/payments/dodo-webhook" | "/api/payments/sandbox-confirm" | "/api/payments/status" | "/api/recovery/claim" | "/api/recovery/create" | "/api/reigns/[id]" | "/api/session" | "/api/share-card/[id]" | "/api/siege/attack" | "/api/siege/entitlements" | "/api/siege/queue" | "/api/siege/turn/cancel" | "/api/siege/turn/claim" | "/api/world"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/assets/[...key]": { "key": string[]; }
  "/api/assets/upload": {}
  "/api/contributors": {}
  "/api/coronation/identity": {}
  "/api/defense/place": {}
  "/api/events": {}
  "/api/history": {}
  "/api/payments/attack-checkout": {}
  "/api/payments/dodo-webhook": {}
  "/api/payments/sandbox-confirm": {}
  "/api/payments/status": {}
  "/api/recovery/claim": {}
  "/api/recovery/create": {}
  "/api/reigns/[id]": { "id": string; }
  "/api/session": {}
  "/api/share-card/[id]": { "id": string; }
  "/api/siege/attack": {}
  "/api/siege/entitlements": {}
  "/api/siege/queue": {}
  "/api/siege/turn/cancel": {}
  "/api/siege/turn/claim": {}
  "/api/world": {}
  "/history": {}
  "/payments/sandbox": {}
  "/privacy": {}
  "/reigns/[id]": { "id": string; }
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
